### ISSUE TITLE
MagicMirror freezes

### ISSUE THREAD

**Issue by johnbosak** [vicmora/MMM-GoogleMapsTraffic#21]
Since I added this module my MagicMirror freezes with a blank screen or freezes with a screen that does not change.  This problem always occurs after 24 hours of starting the MM.  I tried running only this module and the problem still occurs so the problem is in this module. 
 Here is the output from PM2 log file:
[TAILING] Tailing last 10 lines for [mm] process (change the value with --lines option)
/home/pi/.pm2/logs/mm-error-0.log last 10 lines:
0|mm       |     at exports._errnoException (util.js:1026:11)
0|mm       |     at ChildProcess.spawn (internal/child_process.js:313:11)
0|mm       |     at Object.exports.spawn (child_process.js:392:9)
0|mm       |     at Git._schedule (/home/pi/MagicMirror/node_modules/simple-git/src/git.js:1165:42)
0|mm       |     at Git._run (/home/pi/MagicMirror/node_modules/simple-git/src/git.js:1150:12)
0|mm       |     at Git.fetch (/home/pi/MagicMirror/node_modules/simple-git/src/git.js:307:19)
0|mm       |     at /home/pi/MagicMirror/modules/default/updatenotification/node_helper.js:64:11
0|mm       |     at Array.forEach (native)
0|mm       |     at Class.preformFetch (/home/pi/MagicMirror/modules/default/updatenotification/node_helper.js:63:14)
0|mm       |     at Timeout._onTimeout (/home/pi/MagicMirror/modules/default/updatenotification/node_helper.js:86:9) code: 'ENOMEM', errno: 'ENOMEM', syscall: 'spawn' }

/home/pi/.pm2/logs/mm-out-0.log last 10 lines:
0|mm       | If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
0|mm       | 2018-10-23T06:23:19-04:00 6 MMM-WunderGround: null
0|mm       | 2018-10-23T07:02:35-04:00 6 MMM-WunderGround: null
0|mm       | Shutting down server...
0|mm       | Stopping module helper: MMM-MyCommute
0|mm       | Stopping module helper: calendar
0|mm       | Stopping module helper: mmm-systemtemperature
0|mm       | Stopping module helper: updatenotification
0|mm       | Stopping module helper: MMM-WunderGround
0|mm       | Stopping module helper: MMM-GoogleMapsTraffic

[STREAMING] Now streaming realtime logs for [mm] process

**Comment by anthony6608** [comment]
Have you tried disabling the module and letting the others run for 24-48 hours to know for sure its this module? Also maybe you can check your dev console CTRL+SHIFT+I when the mirror is running. See if you notice any errors there?

**Comment by johnbosak** [comment]
Thanks for your reply. I can run all other modules for weeks without a problem. I ran the mirror with only this module and again it failed after 24 hours (blank screen). So I am sure it is this module causing the problem.  I’ll check the dev console.  

John Bosak

**Comment by GavinSS** [comment]
I'm having the same issue. The screen goes blank after about 14 hours. There is an error in the dev console that says the google maps javascript api has been includes multiple times.....  So I checked in the head tag and it is in there multiple times. It appears that each time the map updates it adds another set of script tags for this module.

**Comment by johnbosak** [comment]
This same error has been identified by others as well.  See Console Errors #23 under open issues.
